server:
  domain: "registry.local"
  address: "0.0.0.0"
  port: "5050"
token:
  issuer: "distribution-token-server"
  expiration: 36000
secureModule: false # true if valid tls
tls:
  cert: "/certs/tls.crt"
  key: "/certs/tls.key"
