name: "CI"

on:
  push:
    branches:
      - master
    tags:
      - v*
            
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the image
      run: |
        make TAG_VERSION=${GITHUB_REF##*/} build
    - name: Publish image
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        make TAG_VERSION=${GITHUB_REF##*/} push
        make TAG_VERSION=dev push
        make TAG_VERSION=latest push
